name: Build Plugin

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., 1.0.0 or beta-1)'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version tag (e.g., 1.0.0 or beta-1)'
        required: true
        type: string
    outputs:
      artifact-name:
        description: "Name of the uploaded artifact"
        value: Augmented-Steam-plugin-${{ inputs.version }}
        
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: |
          bun install
          pip install -r requirements.txt

      - name: Build and create zip
        run: python helpers/build_zip.py
        env:
          RELEASE_VERSION: ${{ inputs.version }}
          
      - name: Extract zip for artifact
        run: |
          mkdir -p temp_artifact
          unzip "build/Augmented-Steam-plugin-${{ inputs.version }}.zip" -d temp_artifact/
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Augmented-Steam-plugin-${{ inputs.version }}
          path: temp_artifact/*
          include-hidden-file: true
          if-no-files-found: error
          overwrite: true
